### ISSUE TITLE
Cannot run on Windows if directory contains a space.

### ISSUE THREAD

**Issue by PhonicUK** [maierfelix/tiny-rtx#1] opened 2019-08-19 15:50 UTC
```
C:\Users\FirstName LastName\source\repos\tiny-rtx>npm run start

> tiny-rtx@0.0.1 start C:\Users\FirstName LastName\source\repos\tiny-rtx
> node --experimental-modules ./main.mjs --verbose-log

(node:21384) ExperimentalWarning: The ESM module loader is experimental.
(nvk) Using Vulkan v1.1.114
(nvk) Validation checks are enabled
The system cannot find the path specified.
{ Error: Command failed: C:/Users/FirstName%20LastName/source/repos/tiny-rtx/node_modules/nvk-essentials/bin/win32/bin -v
The system cannot find the path specified.

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at file:///C:/Users/FirstName%20LastName/source/repos/tiny-rtx/node_modules/nvk-essentials/index.mjs:14:15
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
  status: 1,
  signal: null,
  output:
   [ null,
     <Buffer >,
     <Buffer 54 68 65 20 73 79 73 74 65 6d 20 63 61 6e 6e 6f 74 20 66 69 6e 64 20 74 68 65 20 70 61 74 68 20 73 70 65 63 69 66 69 65 64 2e 0d 0a> ],
  pid: 25656,
  stdout: <Buffer >,
  stderr:
   <Buffer 54 68 65 20 73 79 73 74 65 6d 20 63 61 6e 6e 6f 74 20 66 69 6e 64 20 74 68 65 20 70 61 74 68 20 73 70 65 63 69 66 69 65 64 2e 0d 0a> }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-rtx@0.0.1 start: `node --experimental-modules ./main.mjs --verbose-log`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-rtx@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FirstName LastName\AppData\Roaming\npm-cache\_logs\2019-08-19T15_49_31_389Z-debug.log
```

**Comment by PhonicUK** [comment] 2019-08-19 15:52
Moving everything to a directory that has no spaces in makes it all behave, but of course that's annoying ;)

**Comment by htmlgames** [comment] 2019-08-20 21:31
try putting the path part in quotes maybe?

> tiny-rtx@0.0.1 start "C:\Users\FirstName LastName\source\repos\tiny-rtx"

**Comment by maierfelix** [comment] 2019-10-08 10:27
The problem was caused by `nvk-essentials` where the glslangValidator wrapper was broken. `nvk-essentials` now uses a WebAssembly build of glslang, and this bug should be fixed now

**Closed as completed by maierfelix** 2019-10-08 10:27 UTC
